/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.RegisterTokenResponse
import com.weave.network.model.TokenResponse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param registerToken 
 */


data class AuthVerifyPost200Response (

    @SerializedName("accessToken")
    val accessToken: kotlin.String,

    @SerializedName("refreshToken")
    val refreshToken: kotlin.String,

    @SerializedName("registerToken")
    val registerToken: kotlin.String

) {


}

