/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param start 원하는 파트너의 최소 년생
 * @param end 원하는 파트너의 최대 년생
 */


data class BirthYearRange (

    /* 원하는 파트너의 최소 년생 */
    @SerializedName("start")
    val start: kotlin.Int,

    /* 원하는 파트너의 최대 년생 */
    @SerializedName("end")
    val end: kotlin.Int

) {


}

