/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 회사 식별자
 * @param name 회사명
 */


data class Company (

    /* 회사 식별자 */
    @SerializedName("id")
    val id: java.util.UUID,

    /* 회사명 */
    @SerializedName("name")
    val name: kotlin.String

) {


}

