/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param imageId 이미지 ID
 * @param extension
 */


data class CompleteProfileImageUploadRequest(

    /* 이미지 ID */
    @SerializedName("imageId")
    val imageId: java.util.UUID,

    @SerializedName("extension")
    val extension: ProfileImageExtension

) {


}

