/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 회사 표시 정보
 *
 * @param id 회사 식별자
 * @param display 화면에 표시될 회사명
 */


data class CompanyDisplayInfo (

    /* 회사 식별자 */
    @SerializedName("id")
    val id: java.util.UUID,

    /* 화면에 표시될 회사명 */
    @SerializedName("display")
    val display: kotlin.String

) {


}

