/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Connection
import com.weave.network.model.ConnectionAttemptStatus

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param status 
 * @param attemptDate 
 * @param createdAt 
 * @param connection 
 */


data class ConnectionAttempt (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("userId")
    val userId: java.util.UUID,

    @SerializedName("status")
    val status: ConnectionAttemptStatus,

    @SerializedName("attemptDate")
    val attemptDate: kotlin.String,

    @SerializedName("createdAt")
    val createdAt: kotlin.String,

    @SerializedName("connection")
    val connection: Connection? = null

) {


}

