/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ConnectionCancellationReason

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param reason 
 * @param createdAt 
 * @param detail 
 */


data class ConnectionCancellation (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("userId")
    val userId: java.util.UUID,

    @SerializedName("reason")
    val reason: ConnectionCancellationReason,

    @SerializedName("createdAt")
    val createdAt: kotlin.String,

    @SerializedName("detail")
    val detail: kotlin.String? = null

) {


}

