/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 커넥션 시도 상태
 *
 * Values: CONNECTING,CONNECTED,FAILED,UNKNOWN
 */

enum class ConnectionAttemptStatus(val value: kotlin.String) {

    @SerializedName(value = "CONNECTING")
    CONNECTING("CONNECTING"),

    @SerializedName(value = "CONNECTED")
    CONNECTED("CONNECTED"),

    @SerializedName(value = "FAILED")
    FAILED("FAILED"),

    @SerializedName(value = "UNKNOWN")
    UNKNOWN("UNKNOWN");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConnectionAttemptStatus) "$data" else null

        /**
         * Returns a valid [ConnectionAttemptStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConnectionAttemptStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

