/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ConnectionCancellation
import com.weave.network.model.Participant

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param partner 
 * @param connectedAt 
 * @param cancellation 
 */


data class Connection (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("partner")
    val partner: Participant? = null,

    @SerializedName("connectedAt")
    val connectedAt: kotlin.String? = null,

    @SerializedName("cancellation")
    val cancellation: ConnectionCancellation? = null

) {


}

