/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 커넥션 취소 사유
 *
 * Values: NO_RESPONSE,FIRST_MESSAGE_TIMEOUT,DUPLICATED,REPORTED,ADMIN_CANCELLATION,ETC,UNKNOWN
 */

enum class ConnectionCancellationReason(val value: kotlin.String) {

    @SerializedName(value = "NO_RESPONSE")
    NO_RESPONSE("NO_RESPONSE"),

    @SerializedName(value = "FIRST_MESSAGE_TIMEOUT")
    FIRST_MESSAGE_TIMEOUT("FIRST_MESSAGE_TIMEOUT"),

    @SerializedName(value = "DUPLICATED")
    DUPLICATED("DUPLICATED"),

    @SerializedName(value = "REPORTED")
    REPORTED("REPORTED"),

    @SerializedName(value = "ADMIN_CANCELLATION")
    ADMIN_CANCELLATION("ADMIN_CANCELLATION"),

    @SerializedName(value = "ETC")
    ETC("ETC"),

    @SerializedName(value = "UNKNOWN")
    UNKNOWN("UNKNOWN");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConnectionCancellationReason) "$data" else null

        /**
         * Returns a valid [ConnectionCancellationReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConnectionCancellationReason? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

