/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param time 에러 발생 시각 (ISO 8601)
 * @param type 에러 유형
 * @param code 에러 코드
 * @param message 상세 에러 메시지
 */


data class ErrorResponse (

    /* 에러 발생 시각 (ISO 8601) */
    @SerializedName("time")
    val time: java.time.OffsetDateTime,

    /* 에러 유형 */
    @SerializedName("type")
    val type: kotlin.String,

    /* 에러 코드 */
    @SerializedName("code")
    val code: kotlin.String,

    /* 상세 에러 메시지 */
    @SerializedName("message")
    val message: kotlin.String? = null

) {


}

