/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 기존 사용자 인증 응답
 *
 * @param accessToken 액세스 토큰
 * @param refreshToken 리프레시 토큰
 * @param accessTokenExpiresIn 액세스 토큰의 유효 기간 (초 단위)
 * @param refreshTokenExpiresIn 리프레시 토큰의 유효 기간 (초 단위)
 */


data class ExistingUserVerifyCodeResponse (

    /* 액세스 토큰 */
    @SerializedName("accessToken")
    val accessToken: kotlin.String,

    /* 리프레시 토큰 */
    @SerializedName("refreshToken")
    val refreshToken: kotlin.String,

    /* 액세스 토큰의 유효 기간 (초 단위) */
    @SerializedName("accessTokenExpiresIn")
    val accessTokenExpiresIn: kotlin.Int? = null,

    /* 리프레시 토큰의 유효 기간 (초 단위) */
    @SerializedName("refreshTokenExpiresIn")
    val refreshTokenExpiresIn: kotlin.Int? = null

) {


}

