/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Company

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param company 
 */


data class GetCompanyDetailsResponse (

    @SerializedName("company")
    val company: Company

) {


}

