/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Message

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param messages 
 * @param next 다음 페이지를 위한 키, 더 이상 결과가 없으면 null
 */


data class GetChannelMessagesResponse (

    @SerializedName("messages")
    val messages: kotlin.collections.List<Message>? = null,

    /* 다음 페이지를 위한 키, 더 이상 결과가 없으면 null */
    @SerializedName("next")
    val next: java.util.UUID? = null

) {


}

