/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.UserDesiredPartner
import com.weave.network.model.UserProfile

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 사용자 이름
 * @param phoneNumber 사용자의 전화번호 (한국 휴대폰 번호 형식)
 * @param profile 
 * @param desiredPartner 
 * @param id 사용자 식별자
 */


data class GetMyUserInfoResponse (

    /* 사용자 이름 */
    @SerializedName("name")
    val name: kotlin.String,

    /* 사용자의 전화번호 (한국 휴대폰 번호 형식) */
    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String,

    @SerializedName("profile")
    val profile: UserProfile,

    @SerializedName("desiredPartner")
    val desiredPartner: UserDesiredPartner,

    /* 사용자 식별자 */
    @SerializedName("id")
    val id: java.util.UUID? = null

) {


}

