/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ConnectionAttempt

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param connectionAttempt 
 */


data class GetMyConnectionResponse (

    @SerializedName("connectionAttempt")
    val connectionAttempt: ConnectionAttempt

) {


}

