/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ProfileImageExtension

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param imageId 이미지 ID
 * @param url 업로드 URL
 * @param extension 
 * @param uploadExpiresIn 업로드 유효 시간 (초 단위)
 */


data class GetProfileImageUploadUrlResponse (

    /* 이미지 ID */
    @SerializedName("imageId")
    val imageId: java.util.UUID,

    /* 업로드 URL */
    @SerializedName("url")
    val url: kotlin.String,

    @SerializedName("extension")
    val extension: ProfileImageExtension,

    /* 업로드 유효 시간 (초 단위) */
    @SerializedName("uploadExpiresIn")
    val uploadExpiresIn: kotlin.Int

) {


}

