/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 * 직군 표시 정보
 *
 * @param code
 * @param display 화면에 표시될 직군명
 */


data class JobOccupationDisplayInfo(

    @SerializedName("code")
    val code: JobOccupation,

    /* 화면에 표시될 직군명 */
    @SerializedName("display")
    val display: kotlin.String

) {


}

