/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 직업군 분류
 *
 * Values: BUSINESS_ADMIN,SALES_MARKETING,RESEARCH_DEVELOPMENT,IT_INFORMATION,FINANCE_ACCOUNTING,MANUFACTURING_PRODUCTION,EDUCATION_ACADEMIA,LAW_ADMINISTRATION,MILITARY_SECURITY,HEALTHCARE_MEDICAL,MEDIA_ENTERTAINMENT,ARTS_DESIGN,SPORTS,CONSTRUCTION_ENGINEERING,TRANSPORTATION_LOGISTICS,AGRICULTURE_FARMING,SERVICE_INDUSTRY,OTHER
 */

enum class JobOccupation(val value: kotlin.String) {

    @SerializedName(value = "BUSINESS_ADMIN")
    BUSINESS_ADMIN("BUSINESS_ADMIN"),

    @SerializedName(value = "SALES_MARKETING")
    SALES_MARKETING("SALES_MARKETING"),

    @SerializedName(value = "RESEARCH_DEVELOPMENT")
    RESEARCH_DEVELOPMENT("RESEARCH_DEVELOPMENT"),

    @SerializedName(value = "IT_INFORMATION")
    IT_INFORMATION("IT_INFORMATION"),

    @SerializedName(value = "FINANCE_ACCOUNTING")
    FINANCE_ACCOUNTING("FINANCE_ACCOUNTING"),

    @SerializedName(value = "MANUFACTURING_PRODUCTION")
    MANUFACTURING_PRODUCTION("MANUFACTURING_PRODUCTION"),

    @SerializedName(value = "EDUCATION_ACADEMIA")
    EDUCATION_ACADEMIA("EDUCATION_ACADEMIA"),

    @SerializedName(value = "LAW_ADMINISTRATION")
    LAW_ADMINISTRATION("LAW_ADMINISTRATION"),

    @SerializedName(value = "MILITARY_SECURITY")
    MILITARY_SECURITY("MILITARY_SECURITY"),

    @SerializedName(value = "HEALTHCARE_MEDICAL")
    HEALTHCARE_MEDICAL("HEALTHCARE_MEDICAL"),

    @SerializedName(value = "MEDIA_ENTERTAINMENT")
    MEDIA_ENTERTAINMENT("MEDIA_ENTERTAINMENT"),

    @SerializedName(value = "ARTS_DESIGN")
    ARTS_DESIGN("ARTS_DESIGN"),

    @SerializedName(value = "SPORTS")
    SPORTS("SPORTS"),

    @SerializedName(value = "CONSTRUCTION_ENGINEERING")
    CONSTRUCTION_ENGINEERING("CONSTRUCTION_ENGINEERING"),

    @SerializedName(value = "TRANSPORTATION_LOGISTICS")
    TRANSPORTATION_LOGISTICS("TRANSPORTATION_LOGISTICS"),

    @SerializedName(value = "AGRICULTURE_FARMING")
    AGRICULTURE_FARMING("AGRICULTURE_FARMING"),

    @SerializedName(value = "SERVICE_INDUSTRY")
    SERVICE_INDUSTRY("SERVICE_INDUSTRY"),

    @SerializedName(value = "OTHER")
    OTHER("OTHER");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JobOccupation) "$data" else null

        /**
         * Returns a valid [JobOccupation] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JobOccupation? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

