/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param region 
 * @param subRegion 
 */


data class Location (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("region")
    val region: kotlin.String,

    @SerializedName("subRegion")
    val subRegion: kotlin.String

) {


}

