/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param type
 * @param text
 * @param cardColor
 */


data class MessageContent(

    @SerializedName("type")
    val type: MessageContent.Type? = null,

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("cardColor")
    val cardColor: kotlin.String? = null

) {

    /**
     *
     *
     * Values: TEXT,CARD
     */
    enum class Type(val value: kotlin.String) {
        @SerializedName(value = "TEXT")
        TEXT("TEXT"),

        @SerializedName(value = "CARD")
        CARD("CARD");
    }

}

