/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.MessageContent

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id
 * @param channelId
 * @param senderUserId
 * @param content
 * @param createdAt
 */


data class Message(

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("channelId")
    val channelId: java.util.UUID,

    @SerializedName("senderUserId")
    val senderUserId: java.util.UUID,

    @SerializedName("content")
    val content: MessageContent,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime

) {


}

