/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 새 사용자 인증 응답
 *
 * @param registerToken 회원 가입을 위한 토큰
 */


data class NewUserVerificationResponse (

    /* 회원 가입을 위한 토큰 */
    @SerializedName("registerToken")
    val registerToken: kotlin.String? = null

) {


}

