/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ProfileImage
import com.weave.network.model.ProfileWidget
import com.weave.network.model.UserProfileDisplayInfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userId 
 * @param name 사용자 이름
 * @param phoneNumber 사용자의 전화번호 (한국 휴대폰 번호 형식)
 * @param profile 
 * @param profileWidgets 
 * @param profileImages 프로필 이미지 목록
 */


data class Participant (

    @SerializedName("userId")
    val userId: java.util.UUID,

    /* 사용자 이름 */
    @SerializedName("name")
    val name: kotlin.String,

    /* 사용자의 전화번호 (한국 휴대폰 번호 형식) */
    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String,

    @SerializedName("profile")
    val profile: UserProfileDisplayInfo,

    @SerializedName("profileWidgets")
    val profileWidgets: kotlin.collections.List<ProfileWidget>,

    /* 프로필 이미지 목록 */
    @SerializedName("profileImages")
    val profileImages: kotlin.collections.List<ProfileImage>? = null

) {


}

