/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 휴대폰 번호 인증 요청 정보
 *
 * @param phone 
 */


data class PhoneRequest (

    @SerializedName("phone")
    val phone: kotlin.String

) {


}

