/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 선호하는 거리 (내 지역만, 주변 지역 포함, 어디든)
 *
 * Values: ONLY_MY_AREA,INCLUDE_SURROUNDING_REGIONS,ANYWHERE
 */

enum class PreferDistance(val value: kotlin.String) {

    @SerializedName(value = "ONLY_MY_AREA")
    ONLY_MY_AREA("ONLY_MY_AREA"),

    @SerializedName(value = "INCLUDE_SURROUNDING_REGIONS")
    INCLUDE_SURROUNDING_REGIONS("INCLUDE_SURROUNDING_REGIONS"),

    @SerializedName(value = "ANYWHERE")
    ANYWHERE("ANYWHERE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PreferDistance) "$data" else null

        /**
         * Returns a valid [PreferDistance] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PreferDistance? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

