/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.ProfileWidgetType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param content 위젯 내용
 */


data class ProfileWidget (

    @SerializedName("type")
    val type: ProfileWidgetType,

    /* 위젯 내용 */
    @SerializedName("content")
    val content: kotlin.String

) {


}

