/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param id 이미지 식별자
 * @param url 이미지 URL
 * @param extension
 */


data class ProfileImage(

    /* 이미지 식별자 */
    @SerializedName("id")
    val id: java.util.UUID,

    /* 이미지 URL */
    @SerializedName("url")
    val url: java.net.URI,

    @SerializedName("extension")
    val extension: ProfileImageExtension

) {


}

