/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 프로필 위젯 타입
 *
 * Values: HOBBY,STYLE,MBTI,MUSIC,BODY_TYPE,FOOD,MOVIE,DRAMA,BOOK,TRAVEL,DRINKING,MARRIAGE,RELIGION,SMOKING
 */

enum class ProfileWidgetType(val value: kotlin.String) {

    @SerializedName(value = "HOBBY")
    HOBBY("HOBBY"),

    @SerializedName(value = "STYLE")
    STYLE("STYLE"),

    @SerializedName(value = "MBTI")
    MBTI("MBTI"),

    @SerializedName(value = "MUSIC")
    MUSIC("MUSIC"),

    @SerializedName(value = "BODY_TYPE")
    BODY_TYPE("BODY_TYPE"),

    @SerializedName(value = "FOOD")
    FOOD("FOOD"),

    @SerializedName(value = "MOVIE")
    MOVIE("MOVIE"),

    @SerializedName(value = "DRAMA")
    DRAMA("DRAMA"),

    @SerializedName(value = "BOOK")
    BOOK("BOOK"),

    @SerializedName(value = "TRAVEL")
    TRAVEL("TRAVEL"),

    @SerializedName(value = "DRINKING")
    DRINKING("DRINKING"),

    @SerializedName(value = "MARRIAGE")
    MARRIAGE("MARRIAGE"),

    @SerializedName(value = "RELIGION")
    RELIGION("RELIGION"),

    @SerializedName(value = "SMOKING")
    SMOKING("SMOKING");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProfileWidgetType) "$data" else null

        /**
         * Returns a valid [ProfileWidgetType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProfileWidgetType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

