/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 사용자 프로필 정보
 *
 * @param name 
 * @param email 
 */


data class Profile (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("email")
    val email: kotlin.String

) {


}

