/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 토큰 갱신 요청 정보
 *
 * @param refreshToken 
 */


data class RefreshRequest (

    @SerializedName("refreshToken")
    val refreshToken: kotlin.String

) {


}

