/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param refreshToken 유효한 리프레시 토큰
 */


data class RefreshTokenRequest (

    /* 유효한 리프레시 토큰 */
    @SerializedName("refreshToken")
    val refreshToken: kotlin.String? = null

) {


}

