/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Profile

import com.google.gson.annotations.SerializedName

/**
 * 회원가입 완료 요청 정보
 *
 * @param registerToken 
 * @param profile 
 */


data class RegisterRequest (

    @SerializedName("registerToken")
    val registerToken: kotlin.String,

    @SerializedName("profile")
    val profile: Profile

) {


}

