/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * Register Token 응답
 *
 * @param registerToken 
 */


data class RegisterTokenResponse (

    @SerializedName("registerToken")
    val registerToken: kotlin.String

) {


}

