/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param verificationId 인증 요청에 대한 고유 식별자 (UUID 형식)
 */


data class RequestVerification201Response (

    /* 인증 요청에 대한 고유 식별자 (UUID 형식) */
    @SerializedName("verificationId")
    val verificationId: java.util.UUID? = null

) {


}

