/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param phoneNumber 사용자의 전화번호 (한국 휴대폰 번호 형식)
 */


data class RequestVerificationRequest (

    /* 사용자의 전화번호 (한국 휴대폰 번호 형식) */
    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String? = null

) {


}

