/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Company

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companies 
 * @param next 다음 페이지를 위한 키, 더 이상 결과가 없으면 null
 */


data class SearchCompaniesResponse (

    @SerializedName("companies")
    val companies: kotlin.collections.List<Company>,

    /* 다음 페이지를 위한 키, 더 이상 결과가 없으면 null */
    @SerializedName("next")
    val next: java.util.UUID? = null

) {


}

