/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.SystemMessageType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param text 
 * @param nextCardTitle Next card title (only for SYSTEM message with NEXT_CARD type)
 */


data class SendSystemMessageRequest (

    @SerializedName("type")
    val type: SystemMessageType,

    @SerializedName("text")
    val text: kotlin.String,

    /* Next card title (only for SYSTEM message with NEXT_CARD type) */
    @SerializedName("nextCardTitle")
    val nextCardTitle: kotlin.String? = null

) {


}

