/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param authCodeId 인증 요청에 대한 고유 식별자 (UUID 형식)
 * @param userStatus 사용자 상태 (신규 사용자 또는 기존 사용자)
 */


data class SendAuthCodeResponse (

    /* 인증 요청에 대한 고유 식별자 (UUID 형식) */
    @SerializedName("authCodeId")
    val authCodeId: java.util.UUID,

    /* 사용자 상태 (신규 사용자 또는 기존 사용자) */
    @SerializedName("userStatus")
    val userStatus: SendAuthCodeResponse.UserStatus? = null

) {

    /**
     * 사용자 상태 (신규 사용자 또는 기존 사용자)
     *
     * Values: NEW,EXISTING
     */
    enum class UserStatus(val value: kotlin.String) {
        @SerializedName(value = "NEW") NEW("NEW"),
        @SerializedName(value = "EXISTING") EXISTING("EXISTING");
    }

}

