/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 시스템 메시지 타입
 *
 * Values: INFO,NEXT_CARD
 */

enum class SystemMessageType(val value: kotlin.String) {

    @SerializedName(value = "INFO")
    INFO("INFO"),

    @SerializedName(value = "NEXT_CARD")
    NEXT_CARD("NEXT_CARD");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SystemMessageType) "$data" else null

        /**
         * Returns a valid [SystemMessageType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SystemMessageType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

