/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 액세스 토큰 및 리프레시 토큰 응답
 *
 * @param accessToken 
 * @param refreshToken 
 */


data class TokenResponse (

    @SerializedName("accessToken")
    val accessToken: kotlin.String,

    @SerializedName("refreshToken")
    val refreshToken: kotlin.String

) {


}

