/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 * 사용자가 원하는 파트너의 조건
 *
 * @param birthYearRange
 * @param jobOccupations
 * @param preferDistance
 */


data class UpdateUserDesiredPartnerRequest(

    @SerializedName("birthYearRange")
    val birthYearRange: BirthYearRange,

    @SerializedName("jobOccupations")
    val jobOccupations: kotlin.collections.List<JobOccupation>,

    @SerializedName("preferDistance")
    val preferDistance: PreferDistance

) {


}

