/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 *
 *
 * @param desiredPartner
 */


data class UpdateUserDesiredPartnerResponse(

    @SerializedName("desiredPartner")
    val desiredPartner: UserDesiredPartner

) {


}

