/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.Gender
import com.weave.network.model.JobOccupation

import com.google.gson.annotations.SerializedName

/**
 * 사용자 프로필 정보
 *
 * @param gender 
 * @param birthYear 사용자의 출생년도
 * @param companyId 사용자의 회사 ID
 * @param jobOccupation 
 * @param locationIds 사용자의 활동 지역 목록 ID 리스트
 */


data class UserProfile (

    @SerializedName("gender")
    val gender: Gender,

    /* 사용자의 출생년도 */
    @SerializedName("birthYear")
    val birthYear: kotlin.Int,

    /* 사용자의 회사 ID */
    @SerializedName("companyId")
    val companyId: java.util.UUID,

    @SerializedName("jobOccupation")
    val jobOccupation: JobOccupation,

    /* 사용자의 활동 지역 목록 ID 리스트 */
    @SerializedName("locationIds")
    val locationIds: kotlin.collections.List<java.util.UUID>

) {


}

