/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.CompanyDisplayInfo
import com.weave.network.model.Gender
import com.weave.network.model.JobOccupationDisplayInfo
import com.weave.network.model.LocationDisplayInfo

import com.google.gson.annotations.SerializedName

/**
 * 사용자 프로필 표시 정보
 *
 * @param gender 
 * @param birthYear 사용자의 출생년도
 * @param jobOccupation 
 * @param locations 활동 지역 정보 목록
 * @param company 
 */


data class UserProfileDisplayInfo (

    @SerializedName("gender")
    val gender: Gender,

    /* 사용자의 출생년도 */
    @SerializedName("birthYear")
    val birthYear: kotlin.Int,

    @SerializedName("jobOccupation")
    val jobOccupation: JobOccupationDisplayInfo,

    /* 활동 지역 정보 목록 */
    @SerializedName("locations")
    val locations: kotlin.collections.List<LocationDisplayInfo>,

    @SerializedName("company")
    val company: CompanyDisplayInfo? = null

) {


}

