/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 * 회원 가입 시 필요한 사용자 정보
 *
 * @param name 사용자 이름
 * @param profile 
 * @param desiredPartner 
 */


data class UserRegistration (

    /* 사용자 이름 */
    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("profile")
    val profile: UserProfile,

    @SerializedName("desiredPartner")
    val desiredPartner: UserDesiredPartner

) {


}

