/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.weave.network.model.BirthYearRange
import com.weave.network.model.JobOccupation
import com.weave.network.model.PreferDistance

import com.google.gson.annotations.SerializedName

/**
 * 사용자가 원하는 파트너의 조건
 *
 * @param jobOccupations 
 * @param preferDistance 
 * @param birthYearRange 
 */


data class UserDesiredPartner (

    @SerializedName("jobOccupations")
    val jobOccupations: kotlin.collections.List<JobOccupation>,

    @SerializedName("preferDistance")
    val preferDistance: PreferDistance,

    @SerializedName("birthYearRange")
    val birthYearRange: BirthYearRange? = null

) {


}

