/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model

import com.google.gson.annotations.SerializedName

/**
 * 사용자 정보
 *
 * @param id 사용자 고유 식별자
 * @param name 사용자 이름
 * @param profile 
 * @param desiredPartner 
 */


data class User (

    /* 사용자 고유 식별자 */
    @SerializedName("id")
    val id: kotlin.String? = null,

    /* 사용자 이름 */
    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("profile")
    val profile: UserProfile? = null,

    @SerializedName("desiredPartner")
    val desiredPartner: UserDesiredPartner? = null

) {


}

