/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param verificationCode 사용자가 입력한 SMS 인증 코드 (6자리 숫자)
 */


data class VerifyCodeRequest (

    /* 사용자가 입력한 SMS 인증 코드 (6자리 숫자) */
    @SerializedName("verificationCode")
    val verificationCode: kotlin.String

) {


}

