/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.weave.network.model


import com.google.gson.annotations.SerializedName

/**
 * 인증 코드 확인 요청 정보
 *
 * @param phone 
 * @param code 
 */


data class VerificationRequest (

    @SerializedName("phone")
    val phone: kotlin.String,

    @SerializedName("code")
    val code: kotlin.String

) {


}

